### ISSUE TITLE
Installation and initialization

### ISSUE THREAD

**Issue by utensil** [kentookura/forester.nvim#36] opened 2024-10-20 06:18 UTC
Hi,

Following the README, I can't make sure `forester.vim` is always initialized properly when I first open a tree file without manually invoking the `TSInstall` commands. And if I just add the completion configs in `init.lua` etc., `require("forester").setup()` is not guaranteed to have been executed. Directly calling `require("forester").setup()` will also cause an error, unless I have installed tree-sitter for TOML or have opened a TOML file before this (which triggers such a tree-sitter installation). 

It means that in a clean Neovim installation, I have to tweak the config a few times to make sure each part can be executed with their dependencies executed.

Here is the solution I came up with, which works for a clean Neovim installation assuming only lazy.vim. The comments explain every step:

```lua
    {
        "kentookura/forester.nvim",
        -- tried removing this for the auto-completion to have a non-nil `forester_current_config`
        event = "VeryLazy",
        dependencies = {
            { "nvim-telescope/telescope.nvim" },
            { "nvim-treesitter/nvim-treesitter" },
            { "nvim-lua/plenary.nvim" },
            { "hrsh7th/nvim-cmp" }
        },
        -- -- maybe could be even lazier with these, but not working, because `forester` filetype is not registered yet
        -- ft = "tree",
        -- ft = "forester",
        config = function()
            -- can't run this because it treesitter might not be initialized
            -- vim.cmd.TSInstall "toml"

            -- this ensures that the treesitter is initialized, and toml is installed
            local configs = require("nvim-treesitter.configs")
            configs.setup {
                ensure_installed = { "toml" },
                sync_install = true,
            }

            -- this ensures forester is initialized, makeing `forester` tree-sitter available
            require("forester").setup()

            -- can't run this explicitly, because next launch of nvim will ask for reinstallation
            -- vim.cmd.TSInstall "forester"

            -- installs the forester tree-sitter, so the syntax highlighting is available
            configs.setup {
                ensure_installed = { "toml", "forester" },
                sync_install = false,
            }

            -- local foresterCompletionSource = require("forester.completion")

            -- local cmp = require("cmp")

            -- cmp.register_source("forester", foresterCompletionSource)
            -- cmp.setup.filetype("forester", { sources = { { name = "forester", dup = 0 } } })

            -- cmp.setup()
        end,
    },
```

I'm very new to Neovim configuration, so some might be overdone, and too imperative, but it works at least for my clean LunarVim installation.

There is a remaining issue that I have tweaked it work but can't make it work again (I tried to add the auto-complete code in the README here and there.), is that:

The autocompletion setup causes the following error on every auto-complete:

<img width="1519" alt="image" src="https://github.com/user-attachments/assets/0d1a3502-182e-4146-8905-9b112e2bc8de">

which complains that `forester_current_config` is nil.

**Comment by kentookura** [comment] 2024-10-20 11:57
Thanks, this is valuable feedback.

Regarding the errors you see on autocomplete, the plugin attempts to parse a "forest.toml" in the current directory. There is currently no way for the user to configure default toml files on a per path basis, which is probably what we want.

With the current setup, can you confirm that the errors disappear if you run `:Forester config` and pick the relevant entry? I assume you see the error because there is no "forest.toml" in the current directory.

**Comment by kentookura** [comment] 2024-10-20 12:06
In the not too distant future, the cmp source will be removed in favor of LSP-based completions.

As per the [lazy.nvim docs](https://lazy.folke.io/spec/examples), could you specify the branch linked above in your lazy config and report back if there are any issues?

**Comment by utensil** [comment] 2024-10-20 12:59
> With the current setup, can you confirm that the errors disappear if you run `:Forester config` and pick the relevant entry? I assume you see the error because there is no "forest.toml" in the current directory.

Weird, there is indeed `forest.toml` in the current directory... `:Forester config` is silent for me, there is no picking happened.

**Comment by utensil** [comment] 2024-10-20 13:09
> As per the [lazy.nvim docs](https://lazy.folke.io/spec/examples), could you specify the branch linked above in your lazy config and report back if there are any issues?

Specifying the branch as in https://github.com/utensil/forest/commit/7976c93aefc021e58f11c56fc14b90e5eafd5873  seems to be working!  No errors for auto-completion. 👍 👍

**Comment by utensil** [comment] 2024-10-20 13:12
Another unrelated issue about the virtual text, it seems to show only the first word of the titles:

<img width="353" alt="image" src="https://github.com/user-attachments/assets/23435aad-d6bd-4c8b-8a6a-e7ca55e72226">

<img width="522" alt="image" src="https://github.com/user-attachments/assets/e56f35ba-a8ee-404d-9162-a81b51089f63">

**Comment by kentookura** [comment] 2024-10-20 13:18
The titles are computed using the `forester complete` command. If `forester complete` works as expected, the error must be somewhere here:
https://github.com/kentookura/forester.nvim/blob/edf1cf1d8f0a224dc434f7d0a37a0bc3590df91e/lua/forester/bindings.lua#L49-L71
https://github.com/kentookura/forester.nvim/blob/edf1cf1d8f0a224dc434f7d0a37a0bc3590df91e/lua/forester/ui.lua#L20-L48

**Comment by kentookura** [comment] 2024-10-20 13:18
As with autocomplete, this functionality will be subsumed by the lsp server.

**Comment by kentookura** [comment] 2024-10-20 13:21
> Specifying the branch as in [utensil/forest@7976c93](https://github.com/utensil/forest/commit/7976c93aefc021e58f11c56fc14b90e5eafd5873) seems to be working! No errors for auto-completion. 👍 👍

On that branch I am just aborting completion if the current config is nil. It is still weird that it fails to set the config if it is available in the current directory. Do you mind posting the toml file (or a file that exhibits the same behavior)?

**Comment by utensil** [comment] 2024-10-20 13:37
> On that branch I am just aborting completion if the current config is nil. It is still weird that it fails to set the config if it is available in the current directory. Do you mind posting the toml file (or a file that exhibits the same behavior)?

The toml file is https://github.com/utensil/forest/blob/main/forest.toml  .

And I open nvim by first `cd` into the forest directory then `nvim .`. So working directory should be correct.

**Comment by utensil** [comment] 2024-10-20 13:39
> The titles are computed using the `forester complete` command. If `forester complete` works as expected, the error must be somewhere here

Ah, indeed, `forester complete` is not working as expected:

<img width="310" alt="image" src="https://github.com/user-attachments/assets/a89d33d4-723e-49ae-a637-9c82f21f2dfe">

It shows only the first word or symbol.

**Comment by utensil** [comment] 2024-10-20 13:41
> As with autocomplete, this functionality will be subsumed by the lsp server.

I'm looking forward to the lsp server, I believe it's the more promising future for both noevim and vscode.

I thought about building it based on https://github.com/latex-lsp/texlab .

**Comment by kentookura** [comment] 2024-10-20 13:53
https://git.sr.ht/~jonsterling/ocaml-forester/log/lsp :)

Please note that in order for this to become an effective and responsive tool, many improvements need to be made to the compiler infrastructure. That branch is just what is possible *without* modifying the compiler architecture. Before adding many features to the lsp, I want to solve those harder problems.

**Comment by utensil** [comment] 2024-10-20 14:53
Now I'm fighting a new error:

<img width="1739" alt="image" src="https://github.com/user-attachments/assets/6b01fae6-2763-4332-bef4-cb86afad450c">

Everytime I type something, it will trigger auto-completion (from other sources), then such an error comes out, but I manage to type space to ignore the error and accept the auto-complete.

**Comment by kentookura** [comment] 2024-10-20 15:13
I've run into this too. Will investigate!

**Comment by kentookura** [comment] 2024-10-20 15:18
is this fixed on https://github.com/kentookura/forester.nvim/pull/37/commits/f81147fb8996738e40dfba60d4ac395688397a22 ?

**Comment by kentookura** [comment] 2024-10-20 15:20
> It shows only the first word or symbol.

Weird stuff happening with the commas as well...

**Comment by utensil** [comment] 2024-10-20 15:45
> is this fixed on [f81147f](https://github.com/kentookura/forester.nvim/commit/f81147fb8996738e40dfba60d4ac395688397a22) ?

Not really, will try again tomorrow.

**Comment by utensil** [comment] 2024-10-21 08:34
Last night I did a reinstallation of forester.vim by first manually `:Lazy clean forester.nvim` then trigger the installation.

Immediately after, I got some errors again but didn't take a screenshot etc.

Today, there seems to be no error, but autocompletion is also not working. I tried a few reinstallations, no luck.

My last related config modification is [this commit](https://github.com/utensil/forest/commit/7976c93aefc021e58f11c56fc14b90e5eafd5873).

**Comment by utensil** [comment] 2024-10-21 09:28
Now it suddenly works again with the same errors:

<img width="1733" alt="image" src="https://github.com/user-attachments/assets/93d01e7f-f9b8-4c44-a87a-13ed3c85d74b">

**Comment by kentookura** [comment] 2024-10-21 11:14
I think this should be fixed by 088a9d6f7905d156a689e7741347afacb439f633. The plugin uses the `prefixes` key in the config for some autocomplete features, which you did not set. BTW, this is probably the most useful feature of the plugin, being able to transclude new trees without stopping to type.

**Comment by utensil** [comment] 2024-10-21 12:49
I've added the prefixes. But the latest commit seems to cause cmp to be not enable no matter how I try to initialize forester for cmp. I've tried many variants locally, and only when I don't attempt to call ~~register source and~~ filetype, cmp can be enabled (without forester source).

**Comment by utensil** [comment] 2024-10-21 12:59
As lua_ls insists on prompting me that `setup.filetype` doesn't exist, and I can see it in [GitHub code of cmp](https://github.com/hrsh7th/nvim-cmp), eventually I hit `gd` and saw the definition of `setup`, indeed the local version of `cmp` doesn't have `setup.filetype`!

It turns out that my `cmp` is https://github.com/LunarVim/LunarVim/blob/master/lua/lvim/core/cmp.lua 😂

**Comment by kentookura** [comment] 2024-10-21 13:14
I think we are now hitting the fact that the plugin seems to fail to load the config at all. You reported before that `:Forester config` fails, so cmp just does no attempt to complete.

If you have a lua buffer open, you can call `:so` or `:source` to evaluate the current buffer.

If you open the file `lua/forester/config.lua` and add the line `vim.notify(vim.inspect(parse("forest.toml)))` below the definition of parse, you can see if that succeeds

**Comment by utensil** [comment] 2024-10-21 13:39
`:so` seems to succeed:

<img width="838" alt="image" src="https://github.com/user-attachments/assets/7ec1486e-b563-4070-99ad-1b243321873a">

**Comment by kentookura** [comment] 2024-10-21 14:22
I just realised that some bad changes made it into the main branch. Please try again on #37 😬

**Comment by utensil** [comment] 2024-10-23 05:48
Unfortunately, still no luck. I've tried a few reinstallation and variants.

**Comment by kentookura** [comment] 2024-10-23 10:59
Ok 😔  Is your config available? I can try to debug it myself and upstram the fixes. Thanks for your persistence and patience 🙏

**Comment by utensil** [comment] 2024-10-23 14:12
I think the cause is that I'm using LunarVim which has encapsulated cmp.

The config is in my forest repo, but it's tangled with too many other moving parts, so I don't wish to cost you too much time.

The PR can be merged if it works for you. I'll find some time to isolate the issue further. Thank you for your help ❤️

**Comment by utensil** [comment] 2024-10-24 13:48
In case you wonder how I set up nvim for reproducing the issue, I've added the info at the beginning of https://utensil.github.io/forest/uts-002F.xml .

**Comment by kkanarios32** [comment] 2024-10-25 00:57
I have run into the exact same set of issues using lazyvim instead of lunar vim http://www.lazyvim.org/  :laughing:. If it helps at all it appears my forester_current_config is a nil value. This may be because cmp is being loaded on InsertEnter when it needs to be loaded prior to forester?

**Comment by utensil** [comment] 2024-10-25 05:47
I can confirm that the completion doesn't work for LazyVim too. Particularly, as long as

```
  require("cmp").setup.filetype("forester", { sources = { { name = "forester", dup = 0 } } })
```

is in the config, the autocompletion will not work, even for other configured sources, e.g. emoji.

I've updated my forest note above to reflect my setup for both LunarVim and LazyVim. (Now I'm feeling a bit disoriented because of different set of mapping keys between them 😂  )

**Comment by kentookura** [comment] 2024-10-25 07:11
I will try to address the difficulty in debugging by adding some healthchecks. You can already run ':checkhealth forester', but there is almost nothing there. It seems that loading the config is unreliable... Sorry for the hassle!

**Comment by kentookura** [comment] 2024-10-25 11:53
Could these issues be fixed by e5dafd86e316f8c4900d397a2523d0acacc620e4?

**Comment by kkanarios32** [comment] 2024-10-25 13:51
I now get the error when trying to call Forester new
![image](https://github.com/user-attachments/assets/f28f9fa0-63b7-4f9a-b8da-7ec3901b41cb)

**Comment by kentookura** [comment] 2024-10-25 14:26
Have you added your prefixes in the forester config file?

```toml
prefixes = ["foo"]
```

I will make sure that there is an appropriate hint when this is not the case.

**Comment by utensil** [comment] 2024-10-25 14:32
After updating, I'm getting this calling Forester new :

<img width="1736" alt="image" src="https://github.com/user-attachments/assets/7bf360fc-2328-4d73-a313-119525690f75">

after choosing a config, I get

<img width="1839" alt="image" src="https://github.com/user-attachments/assets/62b4a1af-9c3d-4b1d-beab-dccd84e7652a">

instead.

`:Forester browse` works nicely, though.

**Comment by kentookura** [comment] 2024-10-25 14:46
Ok, interesting. If you are using the lazy package manager, you can clone this repo, check out the branch and load the plugin from disk:
```
{  dir = "/home/kento/forester.nvim" },
```

This will make tracking down the issue easier...

I also realized that I am not reloading the forest.toml when it has changed, this should be done as well....

**Comment by kentookura** [comment] 2024-10-25 14:50
Can you confirm that `Forester browse` *no longer* works on the latest commit? It just worked because the `query_all` binding succeeded when the value is nil, and under the hood the forester binary used the default value...

**Comment by kentookura** [comment] 2024-10-25 14:57
@utensil It seems that the root of all your problems come from the fact that the config fails to load.

https://github.com/kentookura/forester.nvim/blob/e06fbeabb6699602c514311aa25f985768bc79cc/lua/forester/config.lua#L106-L114

Can you report what happens when you
- Move into the directory that contains the `forest.toml` file
- Open `config.lua` like this: `:e ~/forester.nvim/lua/forester/config.lua`
- Add the line `set_default_config()` somewhere at the top level below the definition of the function.
- Source the file using `:so`
- Call `:echo g:forester_current_config`
-

**Comment by utensil** [comment] 2024-10-25 15:15
OK, as I do know tha full path is `~/.local/share/lunarvim/site/pack/lazy/opt/forester.nvim/lua/forester/config.lua`, after all these operations, I get a normal

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/27a5449f-a65b-43b7-a35b-74e832538e00">

like last time.

I'm on 

```
branch 36-installation-and-initialization
        commit e81d180
```

**Comment by kkanarios32** [comment] 2024-10-26 18:50
I am able to get everything working but only when I first open the config file and then telescope into the desired tree. Is this the expected behavior? It seems like the toml parser is not available when I directly open the tree file even though it says it is installed with TSInstall.

**Comment by utensil** [comment] 2024-10-27 07:31
> I am able to get everything working but only when I first open the config file and then telescope into the desired tree. Is this the expected behavior? It seems like the toml parser is not available when I directly open the tree file even though it says it is installed with TSInstall.

It's kind of expected as the plugin doesn't handle installing toml parser, that's why I wrote the lua code in this issue, to ensure it, though very hacky and too imperative, but I don't know better to make it more declarative.

I wonder by "have run into the exact same set of issues", do you also mean the auto-completion issue? Have you made the auto-completion work? I'm sure it works somehow because I've made it work once, but I can't reproduce that any more.

**Comment by kentookura** [comment] 2024-10-27 12:40
@kkanarios32 This is only expected if there is no `forest.toml` file in the current directory, as I have not enabled users to configure the plugin to read from a different file by default.

@utensil If the config is not loaded correctly, then autocomplete will not work. I am also unsure with what is going on in your last screenshot, as you can see there is no code trying to index `forester_current_config` on line 72 in `commands.lua`.

**Comment by kentookura** [comment] 2024-10-29 07:19
@utensil The time is nearing where I will be deprecating large swaths of this code in favor of the LSP... I think the only feature that will remain will be the filetype detection and the telescope configurations. Once I am happy with the state of the LSP I will take another hard look at everything here and maybe even rewrite the plugin from scratch...

Sorry I couldn't get stuff to work for you until now, but I am confident that the LSP will radically improve the user experience. Instead of handling errors and nil in lua, we actually have a good programming language to work with. We will even be able to implement custom requests if the base protocol does not suffice for us

**Comment by utensil** [comment] 2024-10-29 09:23
Yeah, looking forward to LSP version, thanks for your patience.

**Comment by utensil** [comment] 2024-11-01 03:58
It occurred to me that the root cause of the issue is that I start nvim with `cd <forest directory> && nvim .`, by changing to `cd <forest directory> && nvim` without `.`, auto-completion and other commands all start working.

Now this is my working setup for lazy:

```lua
    {
        "kentookura/forester.nvim",
        branch = "36-installation-and-initialization",
        event = "VeryLazy",
        dependencies = {
            { "nvim-telescope/telescope.nvim" },
            { "nvim-treesitter/nvim-treesitter" },
            { "nvim-lua/plenary.nvim" },
            { "hrsh7th/nvim-cmp" },
        },
        config = function()
            -- this ensures that the treesitter is initialized, and toml is installed
            local configs = require "nvim-treesitter.configs"
            configs.setup {
                ensure_installed = { "toml" },
                sync_install = true,
            }

            -- this ensures forester is initialized, makeing `forester` tree-sitter available
            require("forester").setup()

            -- installs the forester tree-sitter, so the syntax highlighting is available
            configs.setup {
                ensure_installed = { "toml", "forester" },
                sync_install = false,
            }

            local foresterCompletionSource = require "forester.completion"
            local cmp = require "cmp"
            cmp.register_source("forester", foresterCompletionSource)
            cmp.setup.filetype("forester", { sources = { { name = "forester", dup = 0 } } })
            cmp.setup()
        end,
        keys = {
            { "<localleader>n", "<cmd>Forester new<cr>", desc = "Forester - New" },
            { "<localleader>b", "<cmd>Forester browse<cr>", desc = "Forester - Browse" },
            { "<localleader>l", "<cmd>Forester link_new<cr>", desc = "Forester - Link New" },
            { "<localleader>t", "<cmd>Forester transclude_new<cr>", desc = "Forester - Transclude New" },
        },
    },

```

**Comment by utensil** [comment] 2024-11-01 04:05
Because I have a short script `new.sh` to create a tree based on per-prefix templates, I have also created a handy key mapping to accept input for the prefix (with a default), then run the script and open the created tree file, here it is:

```lua
            {
                "<localleader>c",
                function()
                    local cmd = "./new.sh"
                    local prefix = vim.fn.input "Enter prefix: "
                    if prefix ~= "" then
                        cmd = cmd .. " " .. prefix
                    else
                        cmd = cmd .. " uts"
                    end
                    local file = io.popen(cmd):read "*a"
                    vim.cmd("e " .. file)
                end,
                desc = "Forester - New from Command",
            },
```

**Comment by utensil** [comment] 2024-11-01 05:53
> The titles are computed using the `forester complete` command. If `forester complete` works as expected, the error must be somewhere here

This issue is reported as https://todo.sr.ht/~jonsterling/forester/112 .

**Comment by kentookura** [comment] 2024-11-01 13:21
> It occurred to me that the root cause of the issue is that I start nvim with cd <forest directory> && nvim ., by changing to cd <forest directory> && nvim without ., auto-completion and other commands all start working.

Strange. Very happy that this is now working for you. I will merge the PR and close this issue. Will also take a look at the issue with `forester complete`

**Closed as completed by kentookura** 2024-11-01 13:21 UTC
